In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("world-happiness-report - world-happiness-report.csv")

In [3]:
df.head(5)

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

In [4]:
df.tail(5)

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
1944,Zimbabwe,2016,3.735,7.984,0.768,54.4,0.733,-0.095,0.724,0.738,0.209
1945,Zimbabwe,2017,3.638,8.016,0.754,55.0,0.753,-0.098,0.751,0.806,0.224
1946,Zimbabwe,2018,3.616,8.049,0.775,55.6,0.763,-0.068,0.844,0.710,0.212
1947,Zimbabwe,2019,2.694,7.950,0.759,56.2,0.632,-0.064,0.831,0.716,0.235
1948,Zimbabwe,2020,3.160,7.829,0.717,56.8,0.643,-0.009,0.789,0.703,0.346

In [5]:
df.sample(5)

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
409,Costa Rica,2019,6.998,9.885,0.906,71.50,0.927,-0.146,0.836,0.848,0.303
309,Central African Republic,2010,3.568,7.091,0.483,42.70,0.690,-0.036,0.845,0.523,0.257
1024,Luxembourg,2017,7.061,11.634,0.905,72.60,0.903,0.044,0.330,0.766,0.184
1772,Turkmenistan,2014,5.787,9.427,0.909,60.76,0.805,0.032,NaN,0.695,0.154
1507,Serbia,2019,6.241,9.808,0.903,68.60,0.753,-0.040,0.813,0.509,0.242

In [6]:
df.shape

(1949, 11)

In [7]:
df.columns

Index(['Country name', 'year', 'Life Ladder', 'Log GDP per capita',
       'Social support', 'Healthy life expectancy at birth',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Positive affect', 'Negative affect'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1949 entries, 0 to 1948
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country name                      1949 non-null   object
 1   year                              1949 non-null   int64
 2   Life Ladder                       1949 non-null   float64
 3   Log GDP per capita                1913 non-null   float64
 4   Social support                    1936 non-null   float64
 5   Healthy life expectancy at birth  1894 non-null   float64
 6   Freedom to make life choices      1917 non-null   float64
 7   Generosity                        1860 non-null   float64
 8   Perceptions of corruption         1839 non-null   float64
 9   Positive affect                   1927 non-null   float64
 10  Negative affect                   1933 non-null   float64
dtypes: float64(9), int64(1), object(1)
memory usage: 167.6+ KB

In [9]:
df.dtypes

Country name                         object
year                                  int64
Life Ladder                         float64
Log GDP per capita                  float64
Social support                      float64
Healthy life expectancy at birth    float64
Freedom to make life choices        float64
Generosity                          float64
Perceptions of corruption           float64
Positive affect                     float64
Negative affect                     float64
dtype: object

In [10]:
df.isnull().sum()

Country name                          0
year                                  0
Life Ladder                           0
Log GDP per capita                   36
Social support                       13
Healthy life expectancy at birth     55
Freedom to make life choices         32
Generosity                           89
Perceptions of corruption           110
Positive affect                      22
Negative affect                      16
dtype: int64

In [ ]:
df[df["Log GDP per capita"].isnull()]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
423,Cuba,2006,5.418,NaN,0.970,68.44,0.281,NaN,NaN,0.647,0.277
436,Cyprus,2020,6.260,NaN,0.806,74.10,0.763,NaN,0.816,0.759,0.284
709,Hong Kong S.A.R. of China,2020,5.295,NaN,0.813,NaN,0.705,NaN,0.380,0.609,0.210
771,Iran,2018,4.278,NaN,0.674,66.00,0.603,NaN,0.703,0.553,0.493
772,Iran,2019,5.006,NaN,0.698,66.30,0.623,NaN,0.728,0.600,0.449
773,Iran,2020,4.865,NaN,0.757,66.60,0.600,NaN,0.710,0.582,0.470
918,Kosovo,2020,6.294,NaN,0.792,NaN,0.880,NaN,0.910,0.726,0.201
1087,Malta,2020,6.157,NaN,0.938,72.20,0.931,NaN,0.675,0.601,0.411
1280,North Cyprus,2012,5.463,NaN,0.871,NaN,0.693,NaN,0.855,0.709,0.405
1281,North Cyprus,2013,5.567,NaN,0.869,NaN,0.775,NaN,0.715,0.622,0.443
1282,North Cyprus,2014,5.786,NaN,0.802,NaN,0.830,NaN,0.692,0.724,0.311
1283,North Cyprus,2015,5.843,NaN,0.791,NaN,0.785,NaN,0.659,0.702,0.319
1284,North Cyprus,2016,5.827,NaN,0.808,NaN,0.796,NaN,0.670,0.644,0.346
1285,North Cyprus,2018,5.608,NaN,0.837,NaN,0.797,NaN,0.614,0.480,0.262
1286,North Cyprus,2019,5.467,NaN,0.803,NaN,0.793,NaN,0.640,0.494,0.296
1337,Palestinian Territories,2018,4.554,NaN,0.819,NaN,0.655,NaN,0.814,0.610,0.419
1338,Palestinian Territories,2019,4.483,NaN,0.833,NaN,0.653,NaN,0.829,0.625,0.400
1559,Somalia,2014,5.528,NaN,0.611,49.60,0.874,NaN,0.456,0.834,0.207
1560,Somalia,2015,5.354,NaN,0.599,50.10,0.968,NaN,0.410,0.901,0.187
1561,Somalia,2016,4.668,NaN,0.594,50.00,0.917,NaN,0.441,0.891,0.193
1562,Somaliland region,2009,4.991,NaN,0.880,NaN,0.746,NaN,0.513,0.819,0.112
1563,Somaliland region,2010,4.657,NaN,0.829,NaN,0.820,NaN,0.471,0.769,0.083
1564,Somaliland region,2011,4.931,NaN,0.788,NaN,0.858,NaN,0.357,0.749,0.122
1565,Somaliland region,2012,5.057,NaN,0.786,NaN,0.758,NaN,0.334,0.735,0.152
1596,South Sudan,2014,3.832,NaN,0.545,49.84,0.567,NaN,0.742,0.614,0.428
1597,South Sudan,2015,4.071,NaN,0.585,50.20,0.512,NaN,0.710,0.586,0.450
1598,South Sudan,2016,2.888,NaN,0.532,50.60,0.440,NaN,0.785,0.615,0.549
1599,South Sudan,2017,2.817,NaN,0.557,51.00,0.456,NaN,0.761,0.586,0.517
1679,Taiwan Province of China,2018,6.467,NaN,0.896,NaN,0.741,NaN,0.736,0.848,0.093
1680,Taiwan Province of China,2019,6.537,NaN,0.893,NaN,0.814,NaN,0.718,0.860,0.093
1681,Taiwan Province of China,2020,6.751,NaN,0.901,NaN,0.799,NaN,0.711,0.845,0.083
1891,Venezuela,2018,5.006,NaN,0.887,66.50,0.611,NaN,0.828,0.759,0.374
1892,Venezuela,2019,5.081,NaN,0.888,66.70,0.626,NaN,0.839,0.761,0.351
1893,Venezuela,2020,4.574,NaN,0.805,66.90,0.612,NaN,0.811,0.722,0.396
1918,Yemen,2018,3.058,NaN,0.789,56.70,0.553,NaN,0.793,0.461,0.315
1919,Yemen,2019,4.197,NaN,0.870,57.50,0.651,NaN,0.798,0.543,0.213

In [12]:
df[df["Country name"]=="Cuba"]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
423,Cuba,2006,5.418,NaN,0.97,68.44,0.281,NaN,NaN,0.647,0.277

In [13]:
df=df.dropna(subset="Log GDP per capita")

In [15]:
df=df.drop(columns=["Generosity","Perceptions of corruption"])

In [16]:
df.isnull().sum()

Country name                         0
year                                 0
Life Ladder                          0
Log GDP per capita                   0
Social support                      13
Healthy life expectancy at birth    37
Freedom to make life choices        32
Positive affect                     22
Negative affect                     16
dtype: int64

In [17]:
df[df["Social support"].isnull()]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Positive affect,Negative affect
25,Algeria,2010,5.464,9.287,NaN,64.50,0.593,NaN,NaN
112,Bahrain,2014,6.165,10.783,NaN,67.42,NaN,NaN,NaN
294,Canada,2007,7.482,10.739,NaN,71.66,0.930,0.872,0.257
466,Djibouti,2010,5.006,7.812,NaN,54.30,0.764,NaN,NaN
925,Kuwait,2014,6.180,10.945,NaN,65.80,NaN,NaN,NaN
1164,Morocco,2010,4.383,8.746,NaN,63.50,0.663,NaN,NaN
1310,Oman,2011,6.853,10.382,NaN,65.50,0.916,NaN,0.295
1423,Qatar,2010,6.850,11.520,NaN,66.70,NaN,NaN,NaN
1426,Qatar,2015,6.375,11.486,NaN,68.30,NaN,NaN,NaN
1741,Tunisia,2009,5.025,9.197,NaN,64.96,0.781,NaN,NaN
1814,United Arab Emirates,2014,6.540,11.041,NaN,66.48,NaN,NaN,NaN
1837,United States,2007,7.513,10.933,NaN,68.22,0.872,0.829,0.232
1905,Vietnam,2017,5.175,8.876,NaN,67.70,NaN,NaN,NaN

In [27]:
df[df["Country name"]=="Algeria"]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Positive affect,Negative affect
26,Algeria,2011,5.317,9.297,0.810,64.66,0.530,0.550,0.255
27,Algeria,2012,5.605,9.311,0.839,64.82,0.587,0.604,0.230
28,Algeria,2014,6.355,9.335,0.818,65.14,NaN,0.626,0.177
29,Algeria,2016,5.341,9.362,0.749,65.50,NaN,0.661,0.377
30,Algeria,2017,5.249,9.354,0.807,65.70,0.437,0.642,0.289
31,Algeria,2018,5.043,9.348,0.799,65.90,0.583,0.591,0.293
32,Algeria,2019,4.745,9.337,0.803,66.10,0.385,0.585,0.215

In [23]:
df=df.dropna(subset=['Social support'])

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1900 entries, 0 to 1948
Data columns (total 9 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country name                      1900 non-null   object
 1   year                              1900 non-null   int64
 2   Life Ladder                       1900 non-null   float64
 3   Log GDP per capita                1900 non-null   float64
 4   Social support                    1900 non-null   float64
 5   Healthy life expectancy at birth  1863 non-null   float64
 6   Freedom to make life choices      1874 non-null   float64
 7   Positive affect                   1889 non-null   float64
 8   Negative affect                   1894 non-null   float64
dtypes: float64(7), int64(1), object(1)
memory usage: 148.4+ KB

In [25]:
df.isnull().sum()

Country name                         0
year                                 0
Life Ladder                          0
Log GDP per capita                   0
Social support                       0
Healthy life expectancy at birth    37
Freedom to make life choices        26
Positive affect                     11
Negative affect                      6
dtype: int64

In [26]:
df[df["Healthy life expectancy at birth"].isnull()]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Positive affect,Negative affect
699,Hong Kong S.A.R. of China,2006,5.511,10.746,0.812,NaN,0.910,0.723,0.236
700,Hong Kong S.A.R. of China,2008,5.137,10.816,0.840,NaN,0.922,0.719,0.237
701,Hong Kong S.A.R. of China,2009,5.397,10.788,0.835,NaN,0.918,0.762,0.210
702,Hong Kong S.A.R. of China,2010,5.643,10.847,0.857,NaN,0.890,0.710,0.183
703,Hong Kong S.A.R. of China,2011,5.474,10.887,0.846,NaN,0.894,0.734,0.196
704,Hong Kong S.A.R. of China,2012,5.484,10.893,0.826,NaN,0.880,0.715,0.183
705,Hong Kong S.A.R. of China,2014,5.458,10.940,0.834,NaN,0.843,0.684,0.243
706,Hong Kong S.A.R. of China,2016,5.498,10.970,0.832,NaN,0.800,0.664,0.213
707,Hong Kong S.A.R. of China,2017,5.362,11.000,0.831,NaN,0.831,0.640,0.201
708,Hong Kong S.A.R. of China,2019,5.659,11.000,0.856,NaN,0.727,0.599,0.358
905,Kosovo,2007,5.104,8.928,0.848,NaN,0.381,0.655,0.237
906,Kosovo,2008,5.522,8.981,0.884,NaN,NaN,NaN,0.318
907,Kosovo,2009,5.891,9.008,0.830,NaN,0.506,0.598,0.169
908,Kosovo,2010,5.177,9.033,0.708,NaN,0.451,0.695,0.118
909,Kosovo,2011,4.860,9.067,0.759,NaN,0.589,0.696,0.124
910,Kosovo,2012,5.640,9.086,0.757,NaN,0.636,0.596,0.100
911,Kosovo,2013,6.126,9.113,0.721,NaN,0.568,0.692,0.203
912,Kosovo,2014,5.000,9.129,0.706,NaN,0.441,0.636,0.206
913,Kosovo,2015,5.077,9.182,0.805,NaN,0.561,0.753,0.180
914,Kosovo,2016,5.759,9.228,0.824,NaN,0.827,0.704,0.150
915,Kosovo,2017,6.149,9.262,0.792,NaN,0.858,0.738,0.186
916,Kosovo,2018,6.392,9.296,0.822,NaN,0.890,0.778,0.170
917,Kosovo,2019,6.425,9.339,0.843,NaN,0.841,0.749,0.141
1330,Palestinian Territories,2011,4.751,8.474,0.751,NaN,0.522,0.567,0.388
1331,Palestinian Territories,2012,4.647,8.531,0.782,NaN,0.542,0.616,0.379
1332,Palestinian Territories,2013,4.844,8.489,0.761,NaN,0.454,0.594,0.365
1333,Palestinian Territories,2014,4.722,8.457,0.775,NaN,0.657,0.565,0.380
1334,Palestinian Territories,2015,4.695,8.480,0.766,NaN,0.556,0.594,0.369
1335,Palestinian Territories,2016,4.907,8.498,0.818,NaN,0.608,0.593,0.378
1336,Palestinian Territories,2017,4.628,8.485,0.824,NaN,0.632,0.597,0.416
1672,Taiwan Province of China,2011,6.309,10.705,0.863,NaN,0.761,0.827,0.112
1673,Taiwan Province of China,2012,6.126,10.716,0.825,NaN,0.698,0.821,0.140
1674,Taiwan Province of China,2013,6.340,10.750,0.817,NaN,0.690,0.846,0.124
1675,Taiwan Province of China,2014,6.363,10.798,0.870,NaN,0.693,0.849,0.108
1676,Taiwan Province of China,2015,6.450,10.842,0.885,NaN,0.701,0.832,0.129
1677,Taiwan Province of China,2016,6.513,10.855,0.895,NaN,0.719,0.833,0.108
1678,Taiwan Province of China,2017,6.359,10.871,0.891,NaN,0.760,0.837,0.114

In [28]:
df[df["Country name"]=="Hong Kong S.A.R. of China"]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Positive affect,Negative affect
699,Hong Kong S.A.R. of China,2006,5.511,10.746,0.812,NaN,0.910,0.723,0.236
700,Hong Kong S.A.R. of China,2008,5.137,10.816,0.840,NaN,0.922,0.719,0.237
701,Hong Kong S.A.R. of China,2009,5.397,10.788,0.835,NaN,0.918,0.762,0.210
702,Hong Kong S.A.R. of China,2010,5.643,10.847,0.857,NaN,0.890,0.710,0.183
703,Hong Kong S.A.R. of China,2011,5.474,10.887,0.846,NaN,0.894,0.734,0.196
704,Hong Kong S.A.R. of China,2012,5.484,10.893,0.826,NaN,0.880,0.715,0.183
705,Hong Kong S.A.R. of China,2014,5.458,10.940,0.834,NaN,0.843,0.684,0.243
706,Hong Kong S.A.R. of China,2016,5.498,10.970,0.832,NaN,0.800,0.664,0.213
707,Hong Kong S.A.R. of China,2017,5.362,11.000,0.831,NaN,0.831,0.640,0.201
708,Hong Kong S.A.R. of China,2019,5.659,11.000,0.856,NaN,0.727,0.599,0.358

In [29]:
df=df[~((df['Country name']=="Hong Kong S.A.R. of China") & (df['Healthy life expectancy at birth'].isna()))]

In [30]:
df.isnull().sum()

Country name                         0
year                                 0
Life Ladder                          0
Log GDP per capita                   0
Social support                       0
Healthy life expectancy at birth    27
Freedom to make life choices        26
Positive affect                     11
Negative affect                      6
dtype: int64

In [31]:
df[df["Country name"]=="Kosovo"]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Positive affect,Negative affect
905,Kosovo,2007,5.104,8.928,0.848,NaN,0.381,0.655,0.237
906,Kosovo,2008,5.522,8.981,0.884,NaN,NaN,NaN,0.318
907,Kosovo,2009,5.891,9.008,0.830,NaN,0.506,0.598,0.169
908,Kosovo,2010,5.177,9.033,0.708,NaN,0.451,0.695,0.118
909,Kosovo,2011,4.860,9.067,0.759,NaN,0.589,0.696,0.124
910,Kosovo,2012,5.640,9.086,0.757,NaN,0.636,0.596,0.100
911,Kosovo,2013,6.126,9.113,0.721,NaN,0.568,0.692,0.203
912,Kosovo,2014,5.000,9.129,0.706,NaN,0.441,0.636,0.206
913,Kosovo,2015,5.077,9.182,0.805,NaN,0.561,0.753,0.180
914,Kosovo,2016,5.759,9.228,0.824,NaN,0.827,0.704,0.150
915,Kosovo,2017,6.149,9.262,0.792,NaN,0.858,0.738,0.186
916,Kosovo,2018,6.392,9.296,0.822,NaN,0.890,0.778,0.170
917,Kosovo,2019,6.425,9.339,0.843,NaN,0.841,0.749,0.141

In [32]:
df=df[~((df['Country name']=="Kosovo") & (df['Healthy life expectancy at birth'].isna()))]

In [33]:
df.isnull().sum()

Country name                         0
year                                 0
Life Ladder                          0
Log GDP per capita                   0
Social support                       0
Healthy life expectancy at birth    14
Freedom to make life choices        25
Positive affect                     10
Negative affect                      6
dtype: int64

In [42]:
df[df["Negative affect"].isnull()]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Positive affect,Negative affect
872,Jordan,2018,4.639,9.196,0.800,66.8,0.762,NaN,NaN
873,Jordan,2019,4.453,9.201,0.793,67.0,0.726,NaN,NaN
874,Jordan,2020,4.094,9.150,0.709,67.2,0.779,NaN,NaN
1062,Maldives,2018,5.198,9.826,0.913,70.6,0.855,NaN,NaN
1380,Philippines,2006,4.670,8.562,0.795,59.8,0.828,0.832,NaN
1753,Turkey,2005,4.719,9.809,0.820,62.6,0.623,0.557,NaN

In [43]:
df[df["Country name"]=="Jordan"]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Positive affect,Negative affect
860,Jordan,2005,6.295,9.246,0.920,63.50,NaN,0.696,0.240
861,Jordan,2007,5.598,9.321,0.841,63.98,0.646,0.683,0.240
862,Jordan,2008,4.930,9.343,0.766,64.22,NaN,0.669,0.331
863,Jordan,2009,6.000,9.347,0.899,64.46,0.771,0.645,0.265
864,Jordan,2010,5.570,9.317,0.918,64.70,0.788,0.643,0.343
865,Jordan,2011,5.539,9.289,0.878,65.00,0.760,0.612,0.260
866,Jordan,2012,5.132,9.261,0.829,65.30,0.693,0.565,0.345
867,Jordan,2013,5.172,9.237,0.840,65.60,0.692,0.684,0.286
868,Jordan,2014,5.333,9.222,0.816,65.90,0.729,0.660,0.313
869,Jordan,2015,5.405,9.207,0.830,66.20,0.767,0.690,0.305
870,Jordan,2016,5.271,9.197,0.820,66.40,0.771,0.641,0.312
871,Jordan,2017,4.808,9.194,0.815,66.60,0.766,0.628,0.392
872,Jordan,2018,4.639,9.196,0.800,66.80,0.762,NaN,NaN
873,Jordan,2019,4.453,9.201,0.793,67.00,0.726,NaN,NaN
874,Jordan,2020,4.094,9.150,0.709,67.20,0.779,NaN,NaN

In [47]:
df["Negative affect"].mean()

np.float64(0.2687525387493319)

In [45]:
df["Negative affect"]=df["Negative affect"].fillna(df["Negative affect"].mean())

In [46]:
df.isnull().sum()

Country name                         0
year                                 0
Life Ladder                          0
Log GDP per capita                   0
Social support                       0
Healthy life expectancy at birth    14
Freedom to make life choices        25
Positive affect                     10
Negative affect                      0
dtype: int64

In [51]:
df[df["Positive affect"].isnull()]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Positive affect,Negative affect
126,Bangladesh,2014,4.636,8.164,0.577,62.38,0.736,NaN,0.231000
135,Belarus,2008,5.463,9.677,0.904,61.70,0.640,NaN,0.246000
264,Cambodia,2007,4.156,7.829,0.675,56.10,0.819,NaN,0.320000
779,Iraq,2013,4.725,9.280,0.728,58.88,NaN,NaN,0.554000
872,Jordan,2018,4.639,9.196,0.800,66.80,0.762,NaN,0.268753
873,Jordan,2019,4.453,9.201,0.793,67.00,0.726,NaN,0.268753
874,Jordan,2020,4.094,9.150,0.709,67.20,0.779,NaN,0.268753
1062,Maldives,2018,5.198,9.826,0.913,70.60,0.855,NaN,0.268753
1311,Pakistan,2005,5.225,8.218,0.591,54.20,0.630,NaN,0.237000
1813,United Arab Emirates,2013,6.621,11.001,0.864,66.46,0.936,NaN,0.291000

In [52]:
df[df["Country name"]=="Bangladesh"]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Positive affect,Negative affect
118,Bangladesh,2006,4.319,7.783,0.672,59.02,0.612,0.600,0.321
119,Bangladesh,2007,4.607,7.839,0.514,59.44,0.605,0.635,0.313
120,Bangladesh,2008,5.052,7.886,0.467,59.86,0.606,0.725,0.232
121,Bangladesh,2009,5.083,7.924,0.528,60.28,0.631,0.670,0.223
122,Bangladesh,2010,4.858,7.967,0.549,60.70,0.659,0.629,0.292
123,Bangladesh,2011,4.986,8.018,0.606,61.12,0.838,0.685,0.235
124,Bangladesh,2012,4.724,8.070,0.582,61.54,0.668,0.714,0.183
125,Bangladesh,2013,4.660,8.116,0.530,61.96,0.742,0.619,0.246
126,Bangladesh,2014,4.636,8.164,0.577,62.38,0.736,NaN,0.231
127,Bangladesh,2015,4.633,8.216,0.601,62.80,0.815,0.635,0.226
128,Bangladesh,2016,4.556,8.274,0.649,63.30,0.875,0.560,0.235
129,Bangladesh,2017,4.310,8.334,0.713,63.80,0.896,0.569,0.214
130,Bangladesh,2018,4.499,8.399,0.706,64.30,0.901,0.541,0.361
131,Bangladesh,2019,5.114,8.467,0.673,64.80,0.902,0.537,0.369
132,Bangladesh,2020,5.280,8.472,0.739,65.30,0.777,0.582,0.332

In [53]:
df=df.dropna(subset=["Positive affect"])

In [54]:
df[df["Positive affect"].isna()]

Empty DataFrame
Columns: [Country name, year, Life Ladder, Log GDP per capita, Social support, Healthy life expectancy at birth, Freedom to make life choices, Positive affect, Negative affect]
Index: []

In [55]:
df.isnull().sum()

Country name                         0
year                                 0
Life Ladder                          0
Log GDP per capita                   0
Social support                       0
Healthy life expectancy at birth    14
Freedom to make life choices        24
Positive affect                      0
Negative affect                      0
dtype: int64

In [56]:
df[df["Freedom to make life choices"].isnull()]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Positive affect,Negative affect
28,Algeria,2014,6.355,9.335,0.818,65.14,NaN,0.626,0.177
29,Algeria,2016,5.341,9.362,0.749,65.50,NaN,0.661,0.377
263,Cambodia,2006,3.569,7.746,0.793,55.30,NaN,0.719,0.341
342,China,2006,4.560,8.696,0.747,66.88,NaN,0.809,0.170
343,China,2007,4.863,8.824,0.811,67.06,NaN,0.817,0.159
350,China,2014,5.196,9.386,0.820,68.24,NaN,0.854,0.112
351,China,2015,5.304,9.449,0.794,68.40,NaN,0.809,0.171
352,China,2016,5.325,9.510,0.742,68.70,NaN,0.826,0.146
500,Egypt,2008,4.632,9.186,0.738,59.88,NaN,0.683,0.301
860,Jordan,2005,6.295,9.246,0.920,63.50,NaN,0.696,0.240
862,Jordan,2008,4.930,9.343,0.766,64.22,NaN,0.669,0.331
949,Laos,2012,4.876,8.611,0.693,56.60,NaN,0.917,0.387
1027,Madagascar,2006,3.980,7.376,0.711,54.04,NaN,0.702,0.161
1184,Myanmar,2014,4.786,8.299,0.774,57.74,NaN,0.858,0.112
1467,Saudi Arabia,2005,7.080,10.699,0.868,63.50,NaN,0.730,0.243
1694,Tajikistan,2018,5.497,8.082,0.875,64.10,NaN,0.695,0.220
1695,Tajikistan,2019,5.464,8.126,0.880,64.40,NaN,0.729,0.178
1696,Tajikistan,2020,5.373,8.080,0.790,64.70,NaN,0.749,0.344
1768,Turkmenistan,2009,6.568,8.989,0.924,59.44,NaN,0.781,0.152
1769,Turkmenistan,2011,5.792,9.182,0.964,60.04,NaN,0.639,0.122
1868,Uzbekistan,2009,5.261,8.400,0.905,62.76,NaN,0.736,0.159
1869,Uzbekistan,2010,5.095,8.445,0.903,63.20,NaN,0.776,0.152
1902,Vietnam,2014,5.085,8.716,0.792,67.14,NaN,0.701,0.241
1903,Vietnam,2015,5.076,8.770,0.849,67.30,NaN,0.642,0.232

In [57]:
df[df["Country name"]=="Algeria"]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Positive affect,Negative affect
26,Algeria,2011,5.317,9.297,0.810,64.66,0.530,0.550,0.255
27,Algeria,2012,5.605,9.311,0.839,64.82,0.587,0.604,0.230
28,Algeria,2014,6.355,9.335,0.818,65.14,NaN,0.626,0.177
29,Algeria,2016,5.341,9.362,0.749,65.50,NaN,0.661,0.377
30,Algeria,2017,5.249,9.354,0.807,65.70,0.437,0.642,0.289
31,Algeria,2018,5.043,9.348,0.799,65.90,0.583,0.591,0.293
32,Algeria,2019,4.745,9.337,0.803,66.10,0.385,0.585,0.215

In [58]:
df["Freedom to make life choices"]=df["Freedom to make life choices"].fillna(df["Freedom to make life choices"].mean())

In [59]:
df.isnull().sum()

Country name                         0
year                                 0
Life Ladder                          0
Log GDP per capita                   0
Social support                       0
Healthy life expectancy at birth    14
Freedom to make life choices         0
Positive affect                      0
Negative affect                      0
dtype: int64

In [60]:
df[df["Country name"]=="Taiwan Province of China"]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Positive affect,Negative affect
1669,Taiwan Province of China,2006,6.189,10.613,0.882,68.68,0.630,0.814,0.094
1670,Taiwan Province of China,2008,5.548,10.606,0.830,69.14,0.642,0.794,0.169
1671,Taiwan Province of China,2010,6.229,10.691,0.831,69.60,0.677,0.845,0.136
1672,Taiwan Province of China,2011,6.309,10.705,0.863,NaN,0.761,0.827,0.112
1673,Taiwan Province of China,2012,6.126,10.716,0.825,NaN,0.698,0.821,0.140
1674,Taiwan Province of China,2013,6.340,10.750,0.817,NaN,0.690,0.846,0.124
1675,Taiwan Province of China,2014,6.363,10.798,0.870,NaN,0.693,0.849,0.108
1676,Taiwan Province of China,2015,6.450,10.842,0.885,NaN,0.701,0.832,0.129
1677,Taiwan Province of China,2016,6.513,10.855,0.895,NaN,0.719,0.833,0.108
1678,Taiwan Province of China,2017,6.359,10.871,0.891,NaN,0.760,0.837,0.114

In [61]:
df[df["Country name"]=="Taiwan Province of China"]["Healthy life expectancy at birth"].mean()

np.float64(69.14)

In [64]:
df.loc[(df["Country name"]=="Taiwan Province of China") & (df["Healthy life expectancy at birth"].isna()),"Healthy life expectancy at birth"]=(69.14)

In [65]:
df.isnull().sum()

Country name                        0
year                                0
Life Ladder                         0
Log GDP per capita                  0
Social support                      0
Healthy life expectancy at birth    7
Freedom to make life choices        0
Positive affect                     0
Negative affect                     0
dtype: int64

In [66]:
df[df["Country name"]=="Palestinian Territories"]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Positive affect,Negative affect
1325,Palestinian Territories,2006,4.716,8.213,0.818,61.780,0.547,0.497,0.431
1326,Palestinian Territories,2007,4.151,8.218,0.712,61.897,0.365,0.566,0.412
1327,Palestinian Territories,2008,4.386,8.276,0.666,62.015,0.358,0.571,0.403
1328,Palestinian Territories,2009,4.470,8.329,0.738,62.132,0.468,0.544,0.466
1329,Palestinian Territories,2010,4.703,8.383,0.822,62.250,0.504,0.628,0.381
1330,Palestinian Territories,2011,4.751,8.474,0.751,NaN,0.522,0.567,0.388
1331,Palestinian Territories,2012,4.647,8.531,0.782,NaN,0.542,0.616,0.379
1332,Palestinian Territories,2013,4.844,8.489,0.761,NaN,0.454,0.594,0.365
1333,Palestinian Territories,2014,4.722,8.457,0.775,NaN,0.657,0.565,0.380
1334,Palestinian Territories,2015,4.695,8.480,0.766,NaN,0.556,0.594,0.369
1335,Palestinian Territories,2016,4.907,8.498,0.818,NaN,0.608,0.593,0.378
1336,Palestinian Territories,2017,4.628,8.485,0.824,NaN,0.632,0.597,0.416

In [67]:
df[df["Country name"]=="Palestinian Territories"]["Healthy life expectancy at birth"].mean()

np.float64(62.014799999999994)

In [68]:
df.loc[(df["Country name"]=="Palestinian Territories") & (df["Healthy life expectancy at birth"].isna()),"Healthy life expectancy at birth"]=(62.014799999999994)

In [69]:
df.isnull().sum()

Country name                        0
year                                0
Life Ladder                         0
Log GDP per capita                  0
Social support                      0
Healthy life expectancy at birth    0
Freedom to make life choices        0
Positive affect                     0
Negative affect                     0
dtype: int64

In [70]:
df.to_csv("cleaned_data.csv")