In [29]:
import pandas as pd

In [74]:
df=pd.read_csv("world-happiness-report - world-happiness-report.csv")

In [75]:
df.head(5)

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

In [76]:
df.tail(5)

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
1944,Zimbabwe,2016,3.735,7.984,0.768,54.4,0.733,-0.095,0.724,0.738,0.209
1945,Zimbabwe,2017,3.638,8.016,0.754,55.0,0.753,-0.098,0.751,0.806,0.224
1946,Zimbabwe,2018,3.616,8.049,0.775,55.6,0.763,-0.068,0.844,0.710,0.212
1947,Zimbabwe,2019,2.694,7.950,0.759,56.2,0.632,-0.064,0.831,0.716,0.235
1948,Zimbabwe,2020,3.160,7.829,0.717,56.8,0.643,-0.009,0.789,0.703,0.346

In [77]:
df.sample(5)

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
741,India,2015,4.342,8.604,0.610,58.9,0.777,-0.005,0.776,0.701,0.322
192,Bolivia,2020,5.559,8.998,0.805,64.2,0.877,-0.054,0.868,0.790,0.382
1535,Slovakia,2010,6.052,10.169,0.920,66.8,0.636,-0.101,0.907,0.666,0.277
1350,Panama,2017,6.568,10.324,0.912,69.5,0.900,-0.170,0.841,0.833,0.242
1650,Sweden,2019,7.398,10.882,0.934,72.7,0.942,0.091,0.250,0.826,0.202

In [78]:
df.shape

(1949, 11)

In [79]:
df.columns

Index(['Country name', 'year', 'Life Ladder', 'Log GDP per capita',
       'Social support', 'Healthy life expectancy at birth',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Positive affect', 'Negative affect'],
      dtype='object')

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1949 entries, 0 to 1948
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country name                      1949 non-null   object
 1   year                              1949 non-null   int64
 2   Life Ladder                       1949 non-null   float64
 3   Log GDP per capita                1913 non-null   float64
 4   Social support                    1936 non-null   float64
 5   Healthy life expectancy at birth  1894 non-null   float64
 6   Freedom to make life choices      1917 non-null   float64
 7   Generosity                        1860 non-null   float64
 8   Perceptions of corruption         1839 non-null   float64
 9   Positive affect                   1927 non-null   float64
 10  Negative affect                   1933 non-null   float64
dtypes: float64(9), int64(1), object(1)
memory usage: 167.6+ KB

In [81]:
df.dtypes

Country name                         object
year                                  int64
Life Ladder                         float64
Log GDP per capita                  float64
Social support                      float64
Healthy life expectancy at birth    float64
Freedom to make life choices        float64
Generosity                          float64
Perceptions of corruption           float64
Positive affect                     float64
Negative affect                     float64
dtype: object

In [82]:
df.isnull().sum()

Country name                          0
year                                  0
Life Ladder                           0
Log GDP per capita                   36
Social support                       13
Healthy life expectancy at birth     55
Freedom to make life choices         32
Generosity                           89
Perceptions of corruption           110
Positive affect                      22
Negative affect                      16
dtype: int64

In [83]:
df[df["Log GDP per capita"].isnull()]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
423,Cuba,2006,5.418,NaN,0.970,68.44,0.281,NaN,NaN,0.647,0.277
436,Cyprus,2020,6.260,NaN,0.806,74.10,0.763,NaN,0.816,0.759,0.284
709,Hong Kong S.A.R. of China,2020,5.295,NaN,0.813,NaN,0.705,NaN,0.380,0.609,0.210
771,Iran,2018,4.278,NaN,0.674,66.00,0.603,NaN,0.703,0.553,0.493
772,Iran,2019,5.006,NaN,0.698,66.30,0.623,NaN,0.728,0.600,0.449
773,Iran,2020,4.865,NaN,0.757,66.60,0.600,NaN,0.710,0.582,0.470
918,Kosovo,2020,6.294,NaN,0.792,NaN,0.880,NaN,0.910,0.726,0.201
1087,Malta,2020,6.157,NaN,0.938,72.20,0.931,NaN,0.675,0.601,0.411
1280,North Cyprus,2012,5.463,NaN,0.871,NaN,0.693,NaN,0.855,0.709,0.405
1281,North Cyprus,2013,5.567,NaN,0.869,NaN,0.775,NaN,0.715,0.622,0.443
1282,North Cyprus,2014,5.786,NaN,0.802,NaN,0.830,NaN,0.692,0.724,0.311
1283,North Cyprus,2015,5.843,NaN,0.791,NaN,0.785,NaN,0.659,0.702,0.319
1284,North Cyprus,2016,5.827,NaN,0.808,NaN,0.796,NaN,0.670,0.644,0.346
1285,North Cyprus,2018,5.608,NaN,0.837,NaN,0.797,NaN,0.614,0.480,0.262
1286,North Cyprus,2019,5.467,NaN,0.803,NaN,0.793,NaN,0.640,0.494,0.296
1337,Palestinian Territories,2018,4.554,NaN,0.819,NaN,0.655,NaN,0.814,0.610,0.419
1338,Palestinian Territories,2019,4.483,NaN,0.833,NaN,0.653,NaN,0.829,0.625,0.400
1559,Somalia,2014,5.528,NaN,0.611,49.60,0.874,NaN,0.456,0.834,0.207
1560,Somalia,2015,5.354,NaN,0.599,50.10,0.968,NaN,0.410,0.901,0.187
1561,Somalia,2016,4.668,NaN,0.594,50.00,0.917,NaN,0.441,0.891,0.193
1562,Somaliland region,2009,4.991,NaN,0.880,NaN,0.746,NaN,0.513,0.819,0.112
1563,Somaliland region,2010,4.657,NaN,0.829,NaN,0.820,NaN,0.471,0.769,0.083
1564,Somaliland region,2011,4.931,NaN,0.788,NaN,0.858,NaN,0.357,0.749,0.122
1565,Somaliland region,2012,5.057,NaN,0.786,NaN,0.758,NaN,0.334,0.735,0.152
1596,South Sudan,2014,3.832,NaN,0.545,49.84,0.567,NaN,0.742,0.614,0.428
1597,South Sudan,2015,4.071,NaN,0.585,50.20,0.512,NaN,0.710,0.586,0.450
1598,South Sudan,2016,2.888,NaN,0.532,50.60,0.440,NaN,0.785,0.615,0.549
1599,South Sudan,2017,2.817,NaN,0.557,51.00,0.456,NaN,0.761,0.586,0.517
1679,Taiwan Province of China,2018,6.467,NaN,0.896,NaN,0.741,NaN,0.736,0.848,0.093
1680,Taiwan Province of China,2019,6.537,NaN,0.893,NaN,0.814,NaN,0.718,0.860,0.093
1681,Taiwan Province of China,2020,6.751,NaN,0.901,NaN,0.799,NaN,0.711,0.845,0.083
1891,Venezuela,2018,5.006,NaN,0.887,66.50,0.611,NaN,0.828,0.759,0.374
1892,Venezuela,2019,5.081,NaN,0.888,66.70,0.626,NaN,0.839,0.761,0.351
1893,Venezuela,2020,4.574,NaN,0.805,66.90,0.612,NaN,0.811,0.722,0.396
1918,Yemen,2018,3.058,NaN,0.789,56.70,0.553,NaN,0.793,0.461,0.315
1919,Yemen,2019,4.197,NaN,0.870,57.50,0.651,NaN,0.798,0.543,0.213

In [71]:
df=df.dropna(subset=["Log GDP per capita"])

In [72]:
df.isnull().sum()

Country name                        0
year                                0
Life Ladder                         0
Log GDP per capita                  0
Social support                      0
Healthy life expectancy at birth    0
Freedom to make life choices        0
Generosity                          0
Perceptions of corruption           0
Positive affect                     0
Negative affect                     0
dtype: int64